# Generated by Django 3.0.8 on 2020-08-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200309_0926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='p_subcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='p_type',
        ),
    ]
