# Generated by Django 3.0.8 on 2020-08-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200811_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
